attributes:
- description: Product id
  id: product_id
  labels:
  - description: Product id
    id: product_id
    primary: true
    sourceColumn: product_id
    tags:
    - Products
    title: Product id
  tags:
  - Products
  title: Product id
- description: Product name
  id: product_name
  labels:
  - description: Product name
    id: product_name
    primary: true
    sourceColumn: product_name
    tags:
    - Products
    title: Product name
  tags:
  - Products
  title: Product name
- description: Category
  id: products.category
  labels:
  - description: Category
    id: products.category
    primary: true
    sourceColumn: category
    tags:
    - Products
    title: Category
  tags:
  - Products
  title: Category
dataSourceTableId:
  dataSourceId: demo-ds
  id: products
  type: dataSource
facts: []
grain:
- id: product_id
  type: attribute
id: products
references: []
tags:
- Products
title: Products
